import { ReactElement, useEffect, useState } from "react";
import type { GetStaticProps } from "next";
import type { NextPageWithLayout } from "./_app";

import Layout from "../components/templates/public.main";

import styles from "../styles/Home.module.css";
import Head from "next/head";
import { getLaunches } from "../services/launches";

const Page: NextPageWithLayout = () => {
  const [launches, setLaunches] = useState([]);
  const [filter, setFilter] = useState("all");

  useEffect(() => {
    async function setData() {
      const launchList = await getLaunches();

      if (launchList.length === 0) return;

      if (filter === "all") {
        setLaunches(launchList);
        return;
      }

      if (filter === "fail") {
        setLaunches(launchList.filter((launch) => launch.success === false));
        return;
      }

      if (filter === "success") {
        setLaunches(launchList.filter((launch) => launch.success === true));
        return;
      }
    }

    setData();
  }, [filter]);

  return (
    <>
      <h1 className={styles.title}>
        Welcome to <a href="https://nextjs.org">ABOUT PAGE</a>
      </h1>

      <p className={styles.description}>
        Get started by editing{" "}
        <code className={styles.code}>pages/index.js</code>
      </p>

      <div className={styles.grid}>
        <a href="https://nextjs.org/docs" className={styles.card}>
          <h2>Documentation &rarr;</h2>
          <p>Find in-depth information about Next.js features and API.</p>
        </a>

        <a href="https://nextjs.org/learn" className={styles.card}>
          <h2>Learn &rarr;</h2>
          <p>Learn about Next.js in an interactive course with quizzes!</p>
        </a>

        <a
          href="https://github.com/vercel/next.js/tree/canary/examples"
          className={styles.card}
        >
          <h2>Examples &rarr;</h2>
          <p>Discover and deploy boilerplate example Next.js projects.</p>
        </a>

        <a
          href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
          className={styles.card}
        >
          <h2>Deploy &rarr;</h2>
          <p>Instantly deploy your Next.js site to a public URL with Vercel.</p>
        </a>
      </div>

      <ul>
        {launches.map((launch) => {
          return (
            <li key={launch.id}>
              {launch.name} - {launch.date} - {`${launch.success}`}
            </li>
          );
        })}
      </ul>

      <button type="button" onClick={() => setFilter("all")}>
        Select all
      </button>
      <button type="button" onClick={() => setFilter("success")}>
        Select all success === true
      </button>
      <button type="button" onClick={() => setFilter("fail")}>
        Select all success === false
      </button>
    </>
  );
};

const InPageHead: React.FC = () => {
  return (
    <Head>
      <title>Create Next App 1</title>
      <meta name="description" content="Generated by create next app 1213" />
    </Head>
  );
};

Page.getLayout = function getLayout(page: ReactElement) {
  return (
    <>
      <Layout>
        <InPageHead />
        {page}
      </Layout>
    </>
  );
};

export default Page;
